# mongo
quarkus.mongodb.database=chat-app
quarkus.mongodb.uuid-representation=standard
quarkus.mongodb.devservices.enabled=true

# logging
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.level=DEBUG
quarkus.log.category."io.quarkus.bootstrap.classloading".level=INFO

# security
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.issuer=http://localhost:8080
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
